### PR TITLE
Gulp file watching server files and adding default( I noticed the wat…

### PR DESCRIPTION
**Pull request by esuarezz**
…ching was getting crazy many times if it is not written with this "flow"

Readme update with Angular2-RC5 structure

### CODE REVIEW

**Comment by esuarezz** [comment]
I did this little modifications, about gulp, completely sure about the watching server files, about default, it is up to you if you want to modify it or not.

Failed to parse SourceMap: http://localhost:3000/libs/core-js/client/shim.min.js.map
Failed to parse SourceMap: http://localhost:3000/libs/reflect-metadata/Reflect.js.map

You say it is ok because is not affecting xD but I dont like them to be honest aaha, let's see if we can remove it.

I will try to include general bootstrap css to the project!

**Comment by moizKachwala** [comment]
I have merged the pull request. Also it would be great if you contribute to this seed application. I am planning to add the bundling for production and adding the e2e tests for the same.

**Comment by esuarezz** [comment]
Yes I will contribute for sure =)! I am running a project for my company  using similar  stack you are using here but more focused on ionic for the FE, so when I add something in my project I will bring here too ;).

I will read this weekend about typescript under the hood, to understand it much better and improve the use I am doing myself with it

**Comment by moizKachwala** [comment]
sure let me know if there is anything I can contribute in your project.

**Comment by esuarezz** [comment]
I have noticed when the page is reloaded is adding on the URL a new
/dashboard hehe =')

when ctlr +r or F5, is doing that wrong and then:
 57c2ed7…:19 Uncaught ReferenceError: System is not defined

I removed the default path so it is not adding many times dashboard for example, but then i get this error too..
So perhaps it is a error in that system.config, I will read this days about it to try to remove that "warnings" and check if this is a Angular2 bug or on this config
I think is that issue on the console :P

I have seen the migration to RC5 is not completed, for example router is not RC5, i will check this tomorrow

**Comment by moizKachwala** [comment]
fixed, added # in the url to maintain the uniformity of routes.

**Comment by esuarezz** [comment]
I have to say I dont like hash in URL; their use is removing a lot of advantages such server side rendering for the future ... SEO... and change this later will be not that easy.
I will try to fix it without hash strategy hehe

Then I dont know what is wrong there, but for example if i try to modify the folder heroDetail, I edit for example the name of the folder, I care everything is right but then it is nor working, and im completely sure it is ok, so i think it is something from configuration... but something is wrong there.. I have to build from zero to get the changes right on dist folder, so the watch is not building and transpiling correctly

**Pull request merged**
